---
layout: article
category: Web
date: 2022-06-03
title: try...except...finally statement in Python
excerpt: "try...except...finally statement is used to handle errors and return information."
---
`try...except...finally`statement is used to handle errors and return information. The format is as follows:

```python
try:
	code
except:
	code
finally:
	code
```

`try` indicates attempting to execute this code. If unsuccessful, the `except` section will be returned. However, regardless of the attempted execution result, the content of `finally` will be returned.

For example:

```python
#!/usr/bin/python3

try:
        x>3
except:
        print('error')
finally:
        print('finally')
```

Return:

```bash
$ ./try.py 
error
finally
```